language: android
jdk:
  - oraclejdk8
os:
  - linux

sudo: required

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-22
    - extra-android-m2repository
    - extra-google-m2repository
#    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-google_apis-22

before_cache:
    - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock,
    - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
    - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock

cache:
    directories:
      - ${TRAVIS_BUILD_DIR}/gradle/caches/
      - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/


before_script:
  - echo no | android create avd --force -n test -t "android-22" --abi armeabi-v7a --tag google_apis
#  - echo no | sdkmanager create avd  -n test
  - emulator -avd test  -no-window -camera-back none -camera-front none  &
#  - curl https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/community-cookbooks/android-sdk/files/default/android-wait-for-emulator > android-wait-for-emulator
#  - chmod u+x android-wait-for-emulator
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
#  - sdkmanager --licenses

script:
   - ./gradlew clean build connectedCheck